eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost/eureka/
  instance:
    hostname: localhost
server:
  port: 80
spring:
  application:
    name: discovery
  cloud:
    loadbalancer:
      ribbon:
        # Or remove spring-cloud-starter-netflix-ribbon from your project.
        enabled: false
  profiles:
    active:
      - default
