eureka:
  client:
    fetch_registry: false
    register_with_eureka: false
    service_url:
      default_zone: http://discovery:8080/eureka
server:
  port: 8080
spring:
  application:
    name: discovery