eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://discovery:8080/eureka/
  instance:
    hostname: discovery
server:
  port: 8080
spring:
  application:
    name: discovery
