spring:
  application:
    name: discovery
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    region: default
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
