eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost/eureka/
  instance:
    hostname: localhost
server:
  port: 80
spring:
  application:
    name: discovery
