eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery:8082/eureka/
hystrix:
  command:
    # Service consumer
    consumer:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    # Discovery server
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    # Service provider
    provider:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
server:
  port: 8080
spring:
  application:
    name: gateway
zuul:
  routes:
    # Service consumer
    consumer:
      path: /consumer/**
      sensitive-headers:
        - Authorization
        - Cookie
        - Set-Cookie
      url: http://consumer:8084
    # Discovery server
    discovery:
      path: /discovery/**
      sensitive-headers:
        - Authorization
        - Cookie
        - Set-Cookie
      url: http://discovery:8082
    # Service provider
    provider:
      path: /provider/**
      sensitive-headers:
        - Authorization
        - Cookie
        - Set-Cookie
      url: http://provider:8083
