eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://discovery/eureka/
server:
  port: 80
spring:
  application:
    name: provider
  cloud:
    loadbalancer:
      ribbon:
        # Or remove spring-cloud-starter-netflix-ribbon from your project.
        enabled: false
  profiles:
    active:
      - default
